### ISSUE TITLE
Component파일관리와 nav,footer 코드수정

### ISSUE THREAD

**Issue by nara04040** [f-lab-edu/red-yoo-toss-tech#15]
# Issue: ⚒️Refactor
Main.js에 component를 관리하도록 리팩토링과 Nav-Component,Footer-Component가 return하게 리팩토링

## To-do
- [ ] Main.js 생성 이후 각 Component파일을 import하게 리팩토링
- [ ] HTML에 script태그 링크를 Main.js로 리팩토링
- [ ] Nav-Component, FooterComponent가 해당 코드만 return하게 리팩토링
