### ISSUE TITLE
component를 class형식으로 리팩토링

### ISSUE THREAD

**Issue by nara04040** [f-lab-edu/red-yoo-toss-tech#23]
# Issue: ⚒️Refactor
각 component파일 코드를 class형식으로 리팩토링

## To-do
- [ ] NavComponent 코드 리팩토링
- [ ] FooterComponent 코드 리팩토링
- [ ] MainComponent 코드 리팩토링
