### ISSUE TITLE
router 기능 구현

### ISSUE THREAD

**Issue by nara04040** [f-lab-edu/red-yoo-toss-tech#27]
# Issue: ✨Feat router 기능 구현
vanila javascript로 router기능을 구현한다.

## To-do
- [x] navigation에 존재하는 "디자인", "기술"을 클릭할 때 마다 url이 변경된다.
- [x] 변경된 url을 확인한다.
- [x] routing기능이 어디서 구현되어야 하는지 결정한다.
