### ISSUE TITLE
MOCK_DATA 수정

### ISSUE THREAD

**Issue by nara04040** [f-lab-edu/red-yoo-toss-tech#28]
# Issue: ✨Feat MOCK_DATA에 데이터 추가
MainComponent의 article내용에 관한 데이터 추가

## To-do
- [x] 작성자 이미지 데이터 추가
- [x] 작성자 이름 데이터 추가
- [x] 작성자 직무 데이터 추가
- [x] article내용 추가
- [x] article 코드블럭 추가
