### ISSUE TITLE
TypeScript로 component파일 마이그레이션

### ISSUE THREAD

**Issue by nara04040** [f-lab-edu/red-yoo-toss-tech#44]
# Issue: ✨Refactor
TypeScript로 component파일 마이그레이션 작업

## To-do
- [x] AritcleComponent TypeScript로 작성
- [x] DesignComponent TypeScript로 작성
- [x] FooterComponent TypeScript로 작성
- [x] NavComponent TypeScript로 작성
